// <auto-generated />
using AsyncHotel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AsyncHotel.Migrations
{
    [DbContext(typeof(AsyncInnDBContext))]
    [Migration("20210127033746_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AsyncHotel.Models.Amenity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Heated Bath"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Oil Lamps"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Crawling Claw Control"
                        });
                });

            modelBuilder.Entity("AsyncHotel.Models.Hotels", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "Cityton",
                            Country = "Accordiantica",
                            Name = "The Glorious Accordian",
                            PhoneNumber = "5555555555",
                            State = "New Statewise",
                            StreetAddress = "246513 Street st"
                        },
                        new
                        {
                            ID = 2,
                            City = "Cityton",
                            Country = "Accordiantica",
                            Name = "The Unarmed Crystal",
                            PhoneNumber = "5555555555",
                            State = "New Statewise",
                            StreetAddress = "4864513 Street st"
                        },
                        new
                        {
                            ID = 3,
                            City = "Cityton",
                            Country = "Accordiantica",
                            Name = "Panoramic Goats Pub",
                            PhoneNumber = "5555555555",
                            State = "New Statewise",
                            StreetAddress = "2465489 Street st"
                        });
                });

            modelBuilder.Entity("AsyncHotel.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bedrooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Layout = 0,
                            Nickname = "The Underdark"
                        },
                        new
                        {
                            ID = 2,
                            Layout = 1,
                            Nickname = "Dusty WereRat"
                        },
                        new
                        {
                            ID = 3,
                            Layout = 3,
                            Nickname = "Ancient Red Dragon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
